version: '3'

services:
  db:
    ## Image docs: https://hub.docker.com/_/postgres
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ## https://marcopeg.com/2019/how-to-run-postgres-for-testing-in-docker
    command: -c shared_buffers=500MB -c fsync=off -c log_statement=all
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    
volumes:
  db:
